### ISSUE TITLE
Some files might be missing from the archive

### ISSUE THREAD

**Issue by Ricky-Tigg** [AveYo/MediaCreationTool.bat#140]
**Physical machine**; **Installed OS:** Windows 10 v. 21H2; **Antivirus:** Windows Defender's _Real-time protection_ set to Off. [Script](https://gist.github.com/AveYo/c74dc774a8fb81a332b5d65613187b15)  acquired via _Download ZIP_ link.

Hello. On my machine the **CPU family** is the unique criteria that does not meet Microsoft's requirements. Here are the files contained in folder _c74dc774a8fb81a332b5d65613187b15-9b7f6ea48e08fcd7002c7b9582a8f73b4fb304f1_ extracted; hidden files are shown if existing: _gitattributes_, _MediaCreationTool.bat ..md_.

As I conceived upon that [source](https://www.youtube.com/watch?v=0Djbq7Bogp4&t=538s), the archive contained five files. Nevertheless there are two of them in this archive.

**Comment by AveYo** [comment]
You've missed the notice on the ***gist*** that the code has moved here, on this github project.
Had to be done a while ago, because the gist was timing out, barely functioning due to increased interest after I've added the 11 bypass feature.  

OLD: https://git.io/MediaCreationTool.bat _(shorturl)_
OLD: https://gist.github.com/AveYo/c74dc774a8fb81a332b5d65613187b15
NEW: https://github.com/AveYo/MediaCreationTool.bat <-- you are here-->

**Comment by Ricky-Tigg** [comment]
Things cannot stop moving; here however within Microsoft's family.  Not so long  that wasn't. I learned my lesson.

**Comment by themechanic1970** [comment]
just tried the new one still said no tpm and no secure boot wont load
