### ISSUE TITLE
windows 11 server install failed

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [AveYo/MediaCreationTool.bat#143]
hi,

since I updated the script to the last git, after the scripts run well and the installer is running after 100% it quits with an alert "windows server install failed"

**Comment by ROBERT-MCDOWELL** [comment]
btw it's on a laptop HP envy DV7 uefi compatible but strangely I didn't find anything about TPM in the bios

**Comment by AveYo** [comment]
What are you doing?
run auto upgrade preset in MediaCreationTool.bat?
or
get 11 via Windows Update?

In any case, it seems the bypass worked since setup presents itself as windows server.  
There are various reasons why setup would fail, regardless.
That's why it's recommended to run an in-place repair with the existing windows version.
I would also need the setup logs from `C:\$WINDOWS.~BT\Sources\Panther` to help more.

**Comment by ROBERT-MCDOWELL** [comment]
mmhmm, it seems a problem with my SSD, I tried to start the windows 10 installer and it does not recognize the any hard drive... despite of I installed it 1 week ago.... damn SSD crap....
