### ISSUE TITLE
There is a serious problem about Win 11 Business Edition from Select menu of MediaCreationTool.bat

### ISSUE THREAD

**Issue by GoldenLighter** [AveYo/MediaCreationTool.bat#145]
I downloaded windows 11 ISO image with this bat file.
**Business Edition - Enterprise**
But it seems there is a problem about this iso file.
First of all the command below has error on these files to get windows os versions :
`dism /Get-WimInfo /WimFile: M :\ sources\install.esd`
As you see install extension is esd not wim
Secondly rufus does not show any drop down list related to remove TPM & Secure Boot during create a bootable usb media with this iso.
Means there is a problem about this iso file & rufus can not read it.
After create a bootable usb with MBR format for old pc & reboot from usb it does not work and sticks on press any key to boot from usb page.
What is wrong about "Media Creation Tool"?
Where can i download pure and latest VL windows 11 enterprise iso with no issue?
I want to install that os on an old pc > No UEFI -> No GPT -> So rufus can help me on that.

I downloaded win 10 iso from Select menu of this bat file (Enterprise) and it was ok.
I installed it on my machine.

People say you can not install win 11 without GPT & UEFI and this is not true.
I downloaded win 11 from another place (wim extention) and create a bootable media with MBR format.
Every thing was ok and i had n't any issue during boot with it.

So tell me what is wrong about win 11 iso output of this bat file?

**Comment by AveYo** [comment]
You're barking at the wrong tree.

There is nothing wrong with the iso.
The created 11 iso already bypasses TPM requirements, and it can boot both MBR and UEFI.
You can test that in a VM.

Your issue is using rufus instead of just creating the usb stick directly with the Auto USB choice.

Rufus does not create proper dual MBR + UEFI bootable windows drives by default.
You need to enable a "cheat code" to toggle that scenario on - need to press `Alt` + `E`

The reason given for this behavior is meh, imho.
I always prefer making windows sticks via MCT first, then just overwrite files.
MCT does a more thoroughly check for stick integrity, and makes it dual UEFI + MBR bootable.

**Comment by GoldenLighter** [comment]
My dear friend,
`The created 11 iso already bypasses TPM requirements,`
This means you manipulated something on iso image.
You should n't & you should let people do it by themselves.
Just forget about rufus.
Why your output iso can not handle this command :
` dism /Get-WimInfo /WimFile: M :\ sources\install.esd`
This means i am in the right place for barking :)
Something is wrong about that iso file.
In many forums people are saying use rufus instead of MCT.
By MCT you can download iso or create bootable usb online.
In my area internet speed is not good for that.
So i downloaded iso image in a vps with your tool and downloaded it in my pc.
So tell me step by step :
1- How can i create a correct bootable usb using your iso file?
Means which tool should i use in offline mode?
That tool should handle both UEFI & Legacy BIOS and let me choose between them.
2- How can i check windows OSs in your iso image before create a bootable media?

**Comment by GoldenLighter** [comment]
People #1 choose for create a bootable media is rufus :
[https://www.makeuseof.com/tag/10-tools-make-bootable-usb-iso-file/](https://www.makeuseof.com/tag/10-tools-make-bootable-usb-iso-file/)
I downloaded iso of win11 from another place = VL = Business Edition
And create a MBR bootable usb with it and has no issue after boot.
In that iso Install extension was "wim" and i could check MediaInfo of it in powershell & cmd.

**Comment by GoldenLighter** [comment]
So am i in the right place for bark behind the tree of love?

**Comment by AveYo** [comment]
This project has a readme that you've skipped over.
The script itself has descriptions for the choices that you've also skipped over.
- If you want vanilla MCT iso, use the **MCT Default** choice in the script.
- Alternatively can just rename the script `def MediaCreationTool.bat` and the media created will not include enhancements such as the TPM bypass in 11.
- But most users prefer the enhancements. Specially for 11, the bypass included works in all scenarios, while the standard reg keys rufus uses are known to be ignored on some cases; the  auto.cmd included is also quite handy for upgrades keeping files and apps even if the installed edition differs.

And yes, MCT creates media with `install.esd`, better compressed than wim, almost always fits on FAT32. 
Why is that news to you? bing / google were not helpful?

**dism /Get-WimInfo /WimFile:I:\sources\install.esd**
```bat
Deployment Image Servicing and Management tool
Version: 10.0.25120.1000

Details for image : I:\sources\install.esd

Index : 1
Name : Windows 11 Home
Description : Windows 11 Home
Size : 15,918,540,541 bytes

Index : 2
Name : Windows 11 Home N
Description : Windows 11 Home N
Size : 15,229,765,223 bytes

Index : 3
Name : Windows 11 Home Single Language
Description : Windows 11 Home Single Language
Size : 15,921,439,394 bytes

Index : 4
Name : Windows 11 Education
Description : Windows 11 Education
Size : 16,201,186,274 bytes

Index : 5
Name : Windows 11 Education N
Description : Windows 11 Education N
Size : 15,500,722,223 bytes

Index : 6
Name : Windows 11 Pro
Description : Windows 11 Pro
Size : 16,198,033,078 bytes

Index : 7
Name : Windows 11 Pro N
Description : Windows 11 Pro N
Size : 15,515,196,102 bytes

The operation completed successfully.
```
DISM works just fine with .esd

And FYI, rufus bypass _**manipulates**_ the boot.wim index 2 registry, and is zero-ing sources\appraiserres.dll - it's not walking on water.. 

### You're definitely barking at the wrong tree.

**Comment by GoldenLighter** [comment]
You did the command below on consumer edition of windows 11 iso :
`dism /Get-WimInfo /WimFile:I:\sources\install.esd`
Of course it works.
I am talking about business edition included enterprise edition.
In your script > Win11 > Select > Business Edition
Just download and check it.
And share the results here.
You will see issue is not rufus or me while dism has error on the edition of iso file.

**So i am barking at the right tree of treasury :)**

**Comment by AveYo** [comment]
It's the same thing for business iso. It works.
rufus author confirmed it worked for him as well!
You're using server 2008 as host. Had to find out from the rufus issue. Dude..
The iso made might not even be complete due to missing libraries / incompatibilities
It's an YOU problem.

>@GoldenLighter
You're using old Server OS (on it's last ESU legs, win7 based), not consumer one, any scripts or applications are bound to behave differently.
To make your environment "work" is a futile exercise. Rather just fire up a VM with a proper consumer OS, and everything will work just fine. Tho I believe you only had to use the Default MCT script choice and it would have worked out..

>The sane choice is what Pete Batard recommended: download official iso.
You don't even need business media specifically, modern Windows has virtual editions so you can get consumer media and then just change product key during / after setup.

>Now, stop bothering Pete Batard (and me) with this YOU problem..

**Comment by GoldenLighter** [comment]
I downloaded iso from vps.
And downloaded it again in my pc with latest win 10 os & after that i tried rufus.
For win 10 i did the same action and had no issue with win 10.
So help me to find the problem.

**Comment by GoldenLighter** [comment]
Download win 11 iso should n't be related to os of host.
This is meaningless.
This is not an upgrade.
Also i did it for win 10 > Every thing was fine.

**Comment by AveYo** [comment]
Already gave you the help you need:
use `Default MCT` choice instead of `Select`  
or rename script as `def MediaCreationTool.bat` then `Select` will behave the same.  

That's exactly the same as official MCT - that you should also try instead if above won't work.
if still failing, then try in a consumer OS like a Windows 10 VM.

For the last time,
Official MCT, and this script - a wrapper around MCT - does NOT download an iso from microsoft.
It downloads the ESD release (electronic software distribution) **then** it converts it to iso / usb
The conversion process needs certain libraries present in the OS.
All consumer OS from Windows 7 upwards have what it takes. A 2008 server - IDK.

**Comment by GoldenLighter** [comment]
I did with Default MCT.
It sticks on this page :
https://i.imgur.com/mpAj5hG.png
So why windows server 2008 is the problem?
I am confused about it.
This is not an upgrade.
Should i download win 10 again from another os like win 10, not windows server 2008?
I want to install that windows 10 in 50 clients.
This is why i so scared about it.

**Comment by AveYo** [comment]
https://www.microsoft.com/en-us/software-download/windows11

- > [Create Windows 11 Installation Media](https://go.microsoft.com/fwlink/?linkid=2156295)

open with a browser and run the MCT directly
it might work, it might not
so instead just Download Windows 11 Disk Image (ISO) from the same page

**Comment by GoldenLighter** [comment]
[AveYo](https://github.com/AveYo) I am certainly sure you are a pro programmer and appreciate for helping me.
That link from microsoft only gives consumer edition > home - pro - ....
I want to download business edition -> Enterprise
By the way i am changing download host os to see what will happen about downloaded iso file by your script.
Win 10 iso with your bat file from win server 2008 vps was ok.
I hope i never face any problem in the future about 50 clients.
I did n't download iso from my area because these damn people put a backdoor on all os s.
Some people are like this - Free Food = Zero Security In the future

**Comment by AveYo** [comment]
Microsoft servers hosting these are known to timeout lately.
It does not happen in all regions. Retrying after couple hours / next day usually works.
There's also the possibility of a temporary IP ban due to many requests.

**Comment by GoldenLighter** [comment]
Problem solved - I downloaded it from win 10 & now it is working.
You should **BOLD** this text in your description that **HOST OS** is so important and iso file grab some libraries from **HOST**.

**Comment by AveYo** [comment]
Most people use consumer OS - that has always been the understanding of running Windows. 
Those few using server OS as a desktop already know the quirks and shortcomings and don't go around blaming scripts and software first ;)
Glad you sorted it out!
