### ISSUE TITLE
22621 Stuck in a loop

### ISSUE THREAD

**Issue by LillyWho** [AveYo/MediaCreationTool.bat#146]
[setupact.log](https://github.com/AveYo/MediaCreationTool.bat/files/8760748/setupact.log)
[setuperr.log](https://github.com/AveYo/MediaCreationTool.bat/files/8760753/setuperr.log)

With the hack installed, I try to upgrade using an ISO created with uupdump.net. However, it keeps getting stuck at the choice of "What do you want to do" and on clicking continue "Checking if your PC is ready to upgrade".

**Comment by LillyWho** [comment]
Never mind. The latest version fixed that it seems.

**Comment by LillyWho** [comment]
I'm not sure how it's related, but it does fail to start the SAFE_OS stage though.

**Comment by AveYo** [comment]
Lots of reasons why updating fails independently of bypass script.
The script did it's job.
Everything else is not really my concern, but I have been trying to help people out even if that means combing through 15K+ lines of setup logs.

First, you are using DEV build as a main OS. Filled with games, device drivers & etc.
I admire your confidence in Microsoft in the face of so many known issues. Never mind unknown ones, since you're using an "unsupported" pc. It's a given you should start by disabling any features that more or less depend on supported processors (Core Isolation, Memory integrity, Hyper-V, Sandbox, even WSL).

Secondly, you are using uupdump made iso. uupdump has been going trough some refactoring this month (due to microsoft changing how apps get integrated), so the iso you've made might not work properly for upgrades. I would try with the official [22621 insiders iso](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewiso)

Third, there is a strong possibility your install is "unfix-able". It's just how windows is with data migration on upgrades.
[windows_update_refresh.bat](https://github.com/AveYo/MediaCreationTool.bat/blob/main/bypass11/windows_update_refresh.bat) can help fix some issues, is worth a shot.
The bypass script does enable troubleshooting options to smooth out migration, but you might have to do manual changes.
Like temporarily uninstall software & drivers, specially unsigned ones - can use [Uninstall OEM Drivers - PNPUTIL frontend.bat](https://pastebin.com/699hvCER) to filter such 3rd party drivers. 
I would remove motherboard utilities, then overclocking and game anticheat tools, then device drivers for peripherals, then virtual machines and emulators.

Last but not least, if you have multiple bootable drives, you might want to disconnect / disable extra ones and only leave the one windows is installed to.
