### ISSUE TITLE
Any update on 22H2?

### ISSUE THREAD

**Issue by EliasA97** [AveYo/MediaCreationTool.bat#199]

**Comment by ducarpit** [comment]
Yes, is it possible to add the Windows 11 22H2 download choice? Thanks, Christian

**Comment by TerryUK** [comment]
Well it works for some of us see:

https://www.elevenforum.com/t/installing-windows-11-by-removing-appraiserres-dll-file.3879/page-2

&

He-Pin on this

https://github.com/coofcookie/Windows11Upgrade/issues/35

using ToddandMargo post... problem is it didn't work for them

>>>
Whilst we all wait for this, you can also do an upgrade with:
https://github.com/AveYo/MediaCreationTool.bat/blob/main/bypass11/Skip_TPM_Check_on_Dynamic_Update.cmd

Run the cmd file as administrator.

Open your iso file and run setup. Or use Windows update.
<<<

Also it's covered in a YouTube Video

https://youtu.be/HyeEeJ48sOc

Some conversation with ToddandMargo on the other thread. Seems to work fine on the English International ISO and whatever He-Pin was using as the ISO. Muttering elsewhere on the net about the ISO, could be that specific ISO files generated by Microsoft have an issue as they are packaged up as Windows Server which it isn't. The issue may be poor Microsoft workmanship and not the workaround. It's worth a try.

It’s easy enough to trigger it off:

1. Click code tab above and download the zip file MediaCreationTool.bat-main.zip

Open using Windows Explore zip viewer rather than 7ZIP (right click)

eg. Open with Windows Explorer, go to bypass 11 directory

Click on "Skip_TPM_Check_on_Dynamic_Update.cmd" to run it... didn't need Admin priv to run since set up as that in my case, have admin writes. This makes a change to the registry so that the ISO when run believes you have a compatible machine.

2. Now run the ISO file for Windows 11

For English International it's

Win11_22H2_EnglishInternational_x64.iso

That comes from the Windows 11 download area.

Make sure you select correct language as existing Windows if not it won't give you the option to retain the apps and files.... that is greyed out and you get a clean install.

If it works, it works. All other issue I reckon rest back with Microsoft on the packaging of the ISO for different languages.

**Comment by Ta2i4** [comment]
Similar with #194

**Comment by nando182** [comment]
Looks like the Brazilian Portuguese does show up as "windows server"

**Comment by EliasA97** [comment]
Guys I followed the instructions mentioned on #194 but I'm getting this error and I can't start the installation.

![image](https://user-images.githubusercontent.com/56277356/192419833-18056387-da79-44bf-9c97-9a9f10108429.png)
