### ISSUE TITLE
Suggestion: Windows 8.1

### ISSUE THREAD

**Issue by michelle1574** [AveYo/MediaCreationTool.bat#236]
Please add Windows 8.1 to the list (Update 1-3) and all options.
I think the 1507 installer will be ok

**Comment by stdin82** [comment]
Windows 8.1 ESD links "vg.dl.ws.microsoft.com" are OFF, so there are no point

**Comment by AveYo** [comment]
8.x is also out of support  
but the reason I have skipped it entirely is because it has multiple unfixed elevation-of-privilege flaws - even when you run as limited user, malware can bypass it straight to system and do anything it wants. literally worse than previous 7 or even vista (with server patches) for it's entire lifespan  

and with the recent fuckup of SecureBoot, even 10 is in limbo, microsoft is unwilling to re-release eol esd's

**Comment by michelle1574** [comment]
Hi AveYo, You can get the ESD files from files.rg-adguard.net

**Comment by stdin82** [comment]
> Hi AveYo, You can get the ESD files from files.rg-adguard.net

It only index the files (and provide torrent for some of them), it doesn't host them
https://files.rg-adguard.net/file/411a77d7-208c-a1a0-19ca-486610662472 = link dead
