### ISSUE TITLE
No Windows 11 updates

### ISSUE THREAD

**Issue by ziyaxservers** [AveYo/MediaCreationTool.bat#258]
he i cant update windows 11 to build 22621.0 or later if i check for updates it sas im up to date but my system sas that i am on 22000.1817

**Comment by Martin-Stangl** [comment]
The same for me.

**Comment by nondetect** [comment]
> The same for me.

> he i cant update windows 11 to build 22621.0 or later if i check for updates it sas im up to date but my system sas that i am on 22000.1817

This is not a problem with this utility, but with your hardware/system settings. If you used the utility, you updated without problems. 
Closed issue

**Comment by Martin-Stangl** [comment]
@nondetect We updated successfully to Win 11 using the utility. That's why we are where we are, having the issue described by @ziyaxservers.

I used the same ISO to upgrade to Win 11 on 4 Systems. 1 fulfilling the hardware requirements and 3 needed to modify the ISO with [Quick_11_iso_esd_wim_TPM_toggle.bat](https://github.com/AveYo/MediaCreationTool.bat/blob/main/bypass11/Quick_11_iso_esd_wim_TPM_toggle.bat). In the "standard" installation, windows update finds the 22H2 update, but in none of the 3 installation with the bypassed hardware check.

According to https://www.thewindowsclub.com/windows-11-feature-update-not-showing, this is normal behavior for installations on systems, which do not fulfill the requirements.

I will download a new ISO already including 22H2, modify it with [Quick_11_iso_esd_wim_TPM_toggle.bat](https://github.com/AveYo/MediaCreationTool.bat/blob/main/bypass11/Quick_11_iso_esd_wim_TPM_toggle.bat) and try to update Win 11 to 22H2 using this ISO.

**Comment by ziyaxservers** [comment]
> @nondetect We updated successfully to Win 11 using the utility. That's why we are where we are, having the issue described by @ziyaxservers.
> 
> 
> 
> I used the same ISO to upgrade to Win 11 on 4 Systems. 1 fulfilling the hardware requirements and 3 needed to modify the ISO with [Quick_11_iso_esd_wim_TPM_toggle.bat](https://github.com/AveYo/MediaCreationTool.bat/blob/main/bypass11/Quick_11_iso_esd_wim_TPM_toggle.bat). In the "standard" installation, windows update finds the 22H2 update, but in none of the 3 installation with the bypassed hardware check.
> 
> 
> 
> According to https://www.thewindowsclub.com/windows-11-feature-update-not-showing, this is normal behavior for installations on systems, which do not fulfill the requirements.
> 
> 
> 
> I will download a new ISO already including 22H2, modify it with [Quick_11_iso_esd_wim_TPM_toggle.bat](https://github.com/AveYo/MediaCreationTool.bat/blob/main/bypass11/Quick_11_iso_esd_wim_TPM_toggle.bat) and try to update Win 11 to 22H2 using this ISO.

Nice work

**Comment by Martin-Stangl** [comment]
I updated all 3 systems to 22H2 successfully using the modded ISO. So this seems to be the way to go.
Windows update also provided additional updates afterwards, so it seem this exercise is only required for the major feature updates.

I think this workaround is as good as it gets.
