### ISSUE TITLE
20H2 Download Validation Issues

### ISSUE THREAD

**Issue by nixuno** [AveYo/MediaCreationTool.bat#29]
Error codes 0x8007000D - 0x90002 in Microsoft MCT when validating ISO download for 20H2. Running the following command to generate:

```shell
MediaCreationTool.bat ISO 20H2 Pro
```

**Comment by AveYo** [comment]
language and arch?
could be a server issue as well, it happens from time to time

**Comment by AveYo** [comment]
can confirm this is an issue. will investigate

**Comment by AveYo** [comment]
Issue fixed with the last update.
All 20H2 esd links with size over 4GB have been reverted to 19042.631: en, de, es, pt, fr, it, jp, zh
Sorry, there's no way around it.

Microsoft for some reason hard-coded a maximum of 4GB size for the esd used by MCT, 
anything above will fail validation despite being perfectly fine, with size, hash, digital signature checking out.
It's just MCT that's fundamentally limited, since those oversized esd's get processed just fine by windows update.

Right up Bill's alley "640K out to be enough" that he has been fighting so hard to disprove,
yet the way windows was programmed contradicts him..

On the bright side, this means we get less bloated base esd's ;)
