### ISSUE TITLE
Rolling back

### ISSUE THREAD

**Issue by hellwalker31** [AveYo/MediaCreationTool.bat#31]
Hello.
I was able to install Windows 11 but setup restarted after finish and when it restarted it rolled back at black, opening screen. And tadaa... Windows 10, again with an error which cant remember about it but something "start up" i guess... Any fix or hints or advice?

**Comment by AveYo** [comment]
while the script helps bypassing setup checks to force the install, it won't magically fix any real issues you have with your setup  
some drivers might be incompatible, some antivirus or other software might be incompatible and so on
best bet is to in-place upgrade to the same version you have (10) so that it gets repaired, before attempting 11 again
