### ISSUE TITLE
Windows 11 24h2

### ISSUE THREAD

**Issue by Sam282-web** [AveYo/MediaCreationTool.bat#381]
Wont update from 23h2 to 24h2. Using iso and media creation tool bat. Some error that tells secure boot.

**Comment by javifly** [comment]
I have old Windows 11 21H2 computer and when I go to upgrade my computer to 24H2 it tells me it is a non TMP computer and will not let me upgrade.

Does the tmp hack really work on 24H2?

**Comment by nondetect** [comment]
> Wont update from 23h2 to 24h2. Using iso and media creation tool bat. Some error that tells secure boot.



> I have old Windows 11 21H2 computer and when I go to upgrade my computer to 24H2 it tells me it is a non TMP computer and will not let me upgrade.
> 
> Does the tmp hack really work on 24H2?

First at all you both need to check if your CPU support SSE4.2 instruction set(you can use CPU-Z utility or check out manufacturer site) and if it does, 
Get 11 on 'unsupported' PC via Windows Update or mounted ISO (no patching needed)  
---------------------------------------------------------------------------------  
Step 1: use [Skip_TPM_Check_on_Dynamic_Update.cmd](Skip_TPM_Check_on_Dynamic_Update.cmd) to automatically bypass setup requirements  
_It's a set it and forget it script, with built-in undo - v7 using more reliable /Product Server trick_  
_V9 rebased on cmd due to defender transgression; skips already patched media (0b)_  
Step 2: update


If CPU doesn't have SSE4.2 instruction set, you'll stuck at 23H2

**Comment by javifly** [comment]
I have tried to upgrade to 23h2. It seems that it did let me upgrade to 23H2 without any problem. Now that I am on 23H2 if I try to go to 24H2 I get the same error message again. 

My processor does have compatibility with SSE4.2, I have checked it in CPU-Z. I will have to do the hack you indicate, thanks.

**Comment by javifly** [comment]
I don't think I have understood the steps I have to follow. I am on 23h2 and I have checked that my computer is compatible with SSE4.2 with CPU-Z.

1. I run as administrator Skip_TPM_Check_on_Dynamic_Update.cmd which is located in the bypass11 directory.

2. I run MediaCreationTool.bat as administrator and choose Windows 11 24H2 and the option “Auto update”.

3. It does not install anything...

**Comment by javifly** [comment]
Can someone help me with the process?

**Comment by javifly** [comment]
I am on 23h2 and I have checked that my computer is compatible with SSE4.2 with CPU-Z.

1. I run MediaCreationTool.bat as administrator and choose Windows 11 24H2 and the option “iso”.

2. unzip the iso with 7zip

3. go to cmd with administrator permissions and go to the path of the just unzipped iso. execute setup.exe /product server

although it will put upgrading to windows server ignore the 24h2 will be installed on your windows home, pro, etc...

**Comment by nondetect** [comment]
> windows server

Ignore Windows Server name, it's just for installer, it will upgrade your current revision properly

**Comment by javifly** [comment]
yes!! although it will put upgrading to windows server, the 24h2 will be installed on your windows
