### ISSUE TITLE
I have finally improved the download function, it will try different methods as a fallback

### ISSUE THREAD

**Issue by Human19788** [AveYo/MediaCreationTool.bat#62]
I have finally improved the download function, it will try different methods as a fallback
TPM bypassing is still not ideal, but should work if you use `auto.cmd` to run setup

_Originally posted by @AveYo in https://github.com/AveYo/MediaCreationTool.bat/discussions/10#discussioncomment-1600492_

**Comment by AveYo** [comment]
what do you want me to do with that? I'm in short supply of crystal balls these days..    
get a qr scan app for your phone and scan it, it will direct you to a microsoft support link  
because if that's an windows setup error - it has nothing to do with this script, your problem is elsewhere  
I can only blindly suggest you run a in-place repair with your current windows 10 version

**Comment by AveYo** [comment]
hmm, is this a bot? anyway, blocked since he's not conversating
