### ISSUE TITLE
Maybe a stupid question

### ISSUE THREAD

**Issue by Plexxor** [AveYo/MediaCreationTool.bat#68]
Good day to you sir, my question is how to download the latest MediaCreationTool.bat
2021/12/22  ?

Best rgards

**Comment by AveYo** [comment]
top right corner, green-outline drop-down button `Code` - Download ZIP  

or open MediaCreationTool.bat file in the repository - `raw` - `Ctrl`+`S` to save on your pc from the browser, then edit name and pick Save as type = All Files (*.*) instead of Text files (.txt)  

I am not issuing separate releases since the whole project is in plain-text source code, there are not precompiled binaries to warrant it

**Comment by Plexxor** [comment]
Many thanks for your info.
