### ISSUE TITLE
Windows 11 Insider Preview 22526.1000 (rs_prerelease) update failed

### ISSUE THREAD

**Issue by tonycody** [AveYo/MediaCreationTool.bat#86]
![image](https://user-images.githubusercontent.com/6773121/149064560-f63a5b9c-507d-459e-820d-1ec8dbd09cfb.png)

**Comment by AveYo** [comment]
![latest](https://user-images.githubusercontent.com/12874843/149245627-34449f2a-e28f-4ba0-88ba-a919037a9113.png)

Maybe the latest 22533 will succeed, going fine here..
If not, you should provide some actionable data, else I can't help you:
>zip and attach your setup log folder from C:\$WINDOWS.~BT\Sources\Panther\
(must enable show hidden files in explorer to see it)

**Comment by tonycody** [comment]
> 

I'll try this version

**Comment by tonycody** [comment]
> 
[Panther.zip](https://github.com/AveYo/MediaCreationTool.bat/files/7858917/Panther.zip)

**Comment by tonycody** [comment]
@AveYo The log file has been uploaded

**Comment by AveYo** [comment]
@tonycody dynamic bypass script worked flawlessly

Your setup fails for totally unrelated reasons to this project.

Skimmed through the logs:
- XPS and Print to PDF related drivers appear unsigned/altered (`oem10.inf` `oem9.inf`)
so disable those windows features (Manage optional features - More windows features)
- `Failure while getting the known folder path for CSIDL_PRINTHOOD`
guess it's the fake XPS printer error
- `pSPRemoveUpgradeRegTree: failed to delete reg tree HKLM\SYSTEM\Setup\Upgrade`
this is bad, maybe some tencent "av" crap is blocking access
- `ITaskFolder::DeleteTask failed`
some scheduled tasks is blocked from being deleted, again some tencent "av" crap
- `Cannot write security information for registry key HKLM\SYSTEM\CurrentControlSet\services\TsQBDrv`
most definitely some qq crap driver, just uninstall all tencent stuff before the upgrade
- `CSIAgent: Invalid xml format: FormatException: "script" attribute is mandatory`
never seen that before, maybe some cn localization issue with the name of an installed program 

Since your windows is filled with a lot of garbage from tencent, 
I guess the best would be to download the 22533 iso, mount it and run setup manually from there 
as it can explicitly tell you what's wrong and can overcome more stuff than the automatic windows update can.

**Comment by tonycody** [comment]
> @tonycody dynamic bypass script worked flawlessly
> 
> Your setup fails for totally unrelated reasons to this project.
> 
> Skimmed through the logs:
> 
> * XPS and Print to PDF related drivers appear unsigned/altered (`oem10.inf` `oem9.inf`)
>   so disable those windows features (Manage optional features - More windows features)
> * `Failure while getting the known folder path for CSIDL_PRINTHOOD`
>   guess it's the fake XPS printer error
> * `pSPRemoveUpgradeRegTree: failed to delete reg tree HKLM\SYSTEM\Setup\Upgrade`
>   this is bad, maybe some tencent "av" crap is blocking access
> * `ITaskFolder::DeleteTask failed`
>   some scheduled tasks is blocked from being deleted, again some tencent "av" crap
> * `Cannot write security information for registry key HKLM\SYSTEM\CurrentControlSet\services\TsQBDrv`
>   most definitely some qq crap driver, just uninstall all tencent stuff before the upgrade
> * `CSIAgent: Invalid xml format: FormatException: "script" attribute is mandatory`
>   never seen that before, maybe some cn localization issue with the name of an installed program
> 
> Since your windows is filled with a lot of garbage from tencent, I guess the best would be to download the 22533 iso, mount it and run setup manually from there as it can explicitly tell you what's wrong and can overcome more stuff than the automatic windows update can.

iso reinstall tips clean all data.thank you,I think I know what the problem is

**Comment by AveYo** [comment]
`setupact.log` (also summarized in `setuperr.log`)

**Comment by tonycody** [comment]
> `setupact.log` (also summarized in `setuperr.log`)

thank you!
