### ISSUE TITLE
Intel Xeon E5 2667 v3 Shadow.tech

### ISSUE THREAD

**Issue by Keretux** [AveYo/MediaCreationTool.bat#95]
Windows Server Update/upgrade Problem on Shadow.
Error U 101.
Dont Start in system after Installation system restarts but after this nothing happend.

**Comment by AveYo** [comment]
It looks like the bypass worked fine and you successfully run 11 setup up to the point of restart.
Then setup failed for some reason. 
**That right there is beyond the scope of this project**. 
Windows setup fails fine on it's own if migration hits an incompatible driver, software, etc.
Check Windows setup logs in `C:$WINDOWS.~BT\Sources\Panther` _(hidden dir by default)_  
You might also zip them and attach it here and I will take a look when I can, but again, that's not something caused by this project.
